version: "3"

tasks: 
  build:
    desc: Compile jaffar into ./build
    cmds:
      - deno compile -A -o ./build/lin/projman --target=x86_64-unknown-linux-gnu ./src/main.ts
      - deno compile -A -o ./build/win/projman --target=x86_64-pc-windows-msvc ./src/main.ts
  clean:
    desc: Remove excess files
    cmds:
      - rm -rf ./build ./deno.lock ./.vscode 
  run:
    desc: Run jaffar.
    cmds:
      - deno run -A ./src/main.ts run {{ .CLI_ARGS }}